spring:
  datasource:
    jdbc-url: jdbc:mysql://13.209.174.31:3306/cubox_acs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: acs
    password: cubox2022!
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 15
  datasource2:
    jdbc-url: jdbc:CUBRID:13.209.174.31:30000:GACS_MDM:dba:cuboxdba:?charset=UTF-8
    username: dba
    password: cuboxdba
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    hikari:
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 15
  jpa:
    show-sql: true
    database: mysql
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080

cuboxnia:
  tokenTimeoutMinute: 600
  refreshTokenTimeoutMinute: 1440
  jwtSecretKey: fKbSemnZa9KSNauW